### PR TITLE
Cleaner table implementation, several fixes, more links

### PR DESCRIPTION
**Pull request by henryiii**
The DOI might have been captured from an older version? There shouldn't be a change to it (feel free to fix).

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
No Henry, if you go to Zenodo you will see the following:
"
Cite all versions? You can cite all versions by using the DOI 10.5281/zenodo.1420444. This DOI represents all versions, and will always resolve to the latest one. Read more. 
"

Most people are unaware of this and keep updating DOIs. That's not the best thing to do and why I fix the link to use the all-versions DOI. Please correct your "fix". Thanks.

**Comment by henryiii** [comment]
I didn't touch the DOI. I think there was a PR that was merged while I was editing the file.

**Comment by henryiii** [comment]
Squash when you merge, please. :)

**Comment by eduardo-rodrigues** [comment]
I did merge the PR I had since a while, precisely to fix the DOI to this all-versions DOI. I noticed it had never been merged by somebody apart from me so just went ahead. That's the reason.

Anyway, I still make my point here that most people are now aware of this nice feature of Zenodo DOIs ;-).

And yes, I will squash.

**Review by eduardo-rodrigues — APPROVED** [review]
Looks nicer to me. Thanks for the tidy-up.

**Pull request merged**
